name: Canary Release

on:
  push:
    branches:
      - 'feat/**'
      - 'next'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  canary:
    name: Canary Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm install

      - name: Build tous les packages
        run: |
          pnpm --filter "@zuii/*" --parallel run build
          pnpm run build

      # Publie avec un tag "canary" et une version incluant le hash du commit.
      # Exemple : @zuii/cookie-consent@1.0.2-canary.abc1234
      - name: Publish Canary
        run: |
          pnpm changeset version --snapshot canary
          pnpm changeset publish --tag canary --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
